### PR TITLE
Replace add event steps

### LINKED ISSUE #16: [BUG] Replace steps to add an event
### Description of the bug

Steps are wrong, need to replace by something like:

1. Open a new issue
2. Add event detail in the issue
3. Submit issue

### Please add screenshots (if applicable)

image

### Add any other context about the problem here

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by hariscs**
## Related Issue

- Information about the related issue

Closes: #16  

### Describe the changes you've made
replaced the adding event steps

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

|      Original       |      Updated       |
| :-----------------: | :----------------: |
| original screenshot | updated screenshot |
image

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

File: src/lib/context/ContextWrapper.tsx [hunk 1]
```diff
@@ -51,7 +51,7 @@ const ContextWrapper: FC<{ children: ReactElement }> = ({ children }) => {
 
                 <div className="card max-w-max text-2xl font-medium">
                   <p>
-                    1. Fork the repo{' '}
+                    1. Open a new issue{' '}
                     <a
                       href="https://github.com/WebXDAO/DevConf"
```
Comment (Chandraprakash-Darji) [inline src/lib/context/ContextWrapper.tsx]: change URL to `https://github.com/WebXDAO/DevConf/issues/new?assignees=&labels=add+event&template=add-event.yml&title=Add+%5BEVENT+NAME%5D`.
This will directly redirect to create issue.

File: src/lib/context/ContextWrapper.tsx [hunk 2]
```diff
@@ -60,8 +60,8 @@ const ContextWrapper: FC<{ children: ReactElement }> = ({ children }) => {
                     >
                       WebXDAO/DevConf
                     </a>
-                    <br /> 2. Add Event data in markdown file
-                    <br /> 3. Create pull request and Your event will be live.
+                    <br /> 2. Add event detail in the issue.
```
Comment (stevenovak123) [inline src/lib/context/ContextWrapper.tsx:63]: it should be Event details.

Comment (stevenovak123) [inline src/lib/context/ContextWrapper.tsx]: Please re-write as ``2. Add Event details in the issue.``

**Review by stevenovak123 — CHANGES_REQUESTED** [review]

File: src/lib/context/ContextWrapper.tsx (hunk 2 above)
Comment (iambilalriaz) [inline src/lib/context/ContextWrapper.tsx]: Can you please use block elements instead of using line breaks?

**Review by iambilalriaz — CHANGES_REQUESTED** [review]

File: src/lib/context/ContextWrapper.tsx (hunk 1 above)
Comment (iambilalriaz) [inline src/lib/context/ContextWrapper.tsx]:
```suggestion
                      href="https://github.com/WebXDAO/DevConf/issues"
```

**Review by iambilalriaz — CHANGES_REQUESTED** [review]

File: src/lib/context/ContextWrapper.tsx (hunk 1 above)
Comment (Chandraprakash-Darji) [reply src/lib/context/ContextWrapper.tsx]: Use this link instead `https://github.com/WebXDAO/DevConf/issues/new?assignees=&labels=add+event&template=add-event.yml&title=Add+%5BEVENT+NAME%5D
`

File: src/lib/context/ContextWrapper.tsx (hunk 2 above)
Comment (Chandraprakash-Darji) [reply src/lib/context/ContextWrapper.tsx]: Also can use `<li>` element

Comment (mkubdev) [reply src/lib/context/ContextWrapper.tsx]: Hey, i'm ok with the suggestion. Let's accept the changes and optimize later?

Comment (mkubdev) [reply src/lib/context/ContextWrapper.tsx]:
```suggestion
                    <br /> 2. Add Event details in the issue.
```

**Review by mkubdev — APPROVED** [review]
LGTM ⚡ Thanks everyone for your contribution!!

**Review by shuklaritvik06 — APPROVED** [review]

**Review by stevenovak123 — APPROVED** [review]

**Review by Chandraprakash-Darji — APPROVED** [review]
Approved

**Review by Chandraprakash-Darji — CHANGES_REQUESTED** [review]
Run prettier on this file because prettier is not happy with the code.

**Review by iambilalriaz — APPROVED** [review]

**Review by mkubdev — APPROVED** [review]
LGTM, @Chandraprakash-Darji yup, need prettier!

**Comment by hariscs** [comment]
> Run prettier on this file because prettier is not happy with the code.

how do I run the prettier action ?

**Comment by mkubdev** [comment]
> > Run prettier on this file because prettier is not happy with the code.
> 
> how do I run the prettier action?

Good question! From `package.json` file, we have `format:check` and `format` scripts.
If I test your PR locally, the `format:check` return is all good! So I think we have a problem in the Prettier github workflow.
image

I'm approving this PR and we should now open an issue to fix the prettier workflow wich not matching the repo's prettier config.

Again, thanks a looot @hariscs for your interest and your work ✨ Much appreciated.

**Review by mkubdev — APPROVED** [review]
